version: "0"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:legacy

    ports:
      - 8080:8080

    environment:
      DB_VENDOR: MYSQL

      DB_DATABASE: keycloak

      DB_USER: root

      DB_NAME: keycloak

      DB_PASSWORD: password

      DB_HOST: //aws end point

      KEYCLOAK_USER: admin

      KEYCLOAK_PASSWORD: admin

      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.

      #JDBC_PARAMS: "connectTimeout=30000
